proj1:		proj1.c
		gcc -o proj1 proj1.c
proj2:		proj2.c
		gcc -o proj2 proj2.c
proj3:		proj3.c
		gcc -o proj3 proj3.c

proj4:		proj4.c
		gcc -o proj4 proj4.c

proj5:		proj5.c
		gcc -o proj5 proj5.c

proj6:		proj6.c
		gcc -o proj6 proj6.c

clean:
		rm -f proj1
		rm -f proj2
		rm -f proj3
		rm -f proj4
		rm -f proj5
		rm -f proj6
